### PR TITLE
Add Python CLI

### LINKED ISSUE #47: Allow configuration of taxcalc pinning for B-Tax and OG-USA builds
Currently B-Tax and OG-USA are always pinned to `>=X.Y.Z` version of `taxcalc` where `X.Y.Z` is the latest release of `taxcalc`.  We should provide a way to:

 * [ ] Skip the Tax-Calculator build before OG-USA or B-Tax builds
 * [ ] Give an environment variable or Jenkins argument that is the taxcalc version to which B-Tax and OG-USA should be pinned with `>=`

### PR DESCRIPTION
**Pull request by jbcrail**
This replaces the previous Bash script with a Python CLI. Skipping package builds and uploads is controlled by subcommands, instead of environment variables. See the new README for further information.

This PR partially addresses #45 and #49 and fixes #47, #48, and #51.

### CODE REVIEW

**Comment by martinholmer** [comment]
@jbcrail,  Pull request #52 looks very promising.  It has been almost three weeks since you last made a #52 commit.  Is your development work and testing of this pull request complete?  I was forced to use the old bash shell script for the last Tax-Calculator release, but would like to use your new Python script for the next release.  Is that a reasonable expectation?

**Comment by brittainhard** [comment]
@martinholmer i'm going to review this today and do some test builds using a different label. If everything works, I will merge it shortly after that.

**Comment by brittainhard** [comment]
@jbcrail I installed this locally and it was having problems importing the commands specified in entry_points in setup.py. I fooled around with it but didn't get anywhere. I'll take a look tomorrow and see what I can find.

**Comment by jbcrail** [comment]
@brittainhard Thanks for the suggestion. I updated the package installation.

**Comment by brittainhard** [comment]
Looks good to me otherwise.

**Comment by brittainhard** [comment]
@jbcrail @PeterDSteinberg I don't have write access to this repo so I can't merge it. Want to add me?

**Pull request merged**
