### PR TITLE
Clean up builder script

### PR DESCRIPTION
**Pull request by hdoupe**
This PR aims to resolve the problems brought up in #82.

### CODE REVIEW

**Comment by hdoupe** [comment]
@martinholmer I think some type of "dry-run" configuration might be necessary. To test this script, I swapped out the `run` function for `print` for the following lines of code:

```
    for os_ in OPERATING_SYSTEMS:
        run(f'anaconda --token $TOKEN  upload --force --user {CONDA_USER} '
            f'artifacts/{os_}/{package}-{vers}-py{python_string}_0.tar.bz2')
```

These lines become: 
```
    for os_ in OPERATING_SYSTEMS:
        print(f'anaconda --token $TOKEN  upload --force --user {CONDA_USER} '
            f'artifacts/{os_}/{package}-{vers}-py{python_string}_0.tar.bz2')
```

I then check the output of the script to make sure that the builds are successful and that the upload commands look correct. This solution works well enough but is a little clunky.

The options I'm considering are:
- if `TOKEN` is not set in the environment (or is set to empty string), then print upload commands instead of running them
- add global variable, `UPLOAD` that is set to `True` by default. The user can change the value of this variable and the script will only print the upload commands
- add new commandline argument that specifies whether to run or print upload commands

I like the first option because we should probably check that some type of token variable is set anyways.

What do you think? Do you think a dry-run option should be added? Do you have any other ideas about how this could be configured?

Another question is: Is there a better way to tell if the `anaconda upload` commands will run correctly than just eye-balling them? I can't find any documentation around the `anaconda upload` command. So, I'm not sure if there is a CLI argument to configure this.

**Comment by hdoupe** [comment]
Note: An efficient way to test this is with docker. This will save you time in cleaning up after running the script and guarantee repeatable, reliable runs.

The Dockerfile I've been using is:
```
FROM continuumio/miniconda3

RUN apt --yes update
# install requirements for matplotlib plus vim
RUN apt --yes install libgl1-mesa-glx vim
RUN pip install pyqt5 # req for matplotlib install
RUN conda install --yes conda-build

COPY builder.py /home/builder.py

WORKDIR /home

CMD ["/bin/bash"]
```

You can build this with the following commnad:
```
docker build -t builder:latest ./
```

You can run it with this command:
```
docker run -it builder:latest python builder.py OG-USA ogusa 0.5.11
```

If you edit `builder.py`, then you just re-build the image with the above build command. The software installation layers are cached and will not be re-run. Docker uses the file's checksum to determine whether a cached layer is used or whether to add the updated file to the new image.

**Comment by martinholmer** [comment]
@hdoupe, when I download PR #83 to my computer, here is what I get:
```
iMac:policybrain-builder mrh$ python --version
Python 2.7.15 :: Anaconda custom (64-bit)

iMac:policybrain-builder mrh$ pycodestyle builder.py 

iMac:policybrain-builder mrh$ pylint builder.py 
Using config file /Users/mrh/.pylintrc
************* Module builder
builder.py:77: [E0001(syntax-error), ] invalid syntax (<string>, line 77)
```
I'm totally confused because the one thing you said you were going to do (fix the  available-only-in-3.6 `f-string` business) hasn't been fixed in PR #83.  All of the other changes seem to increase the complexity without adding much benefit.

**Comment by hdoupe** [comment]
@martinholmer said:
> I'm totally confused because the one thing you said you were going to do (fix the available-only-in-3.6 f-string business) hasn't been fixed in PR #83. All of the other changes seem to increase the complexity without adding much benefit.

Sorry for the confusion. I went ahead and fixed some of the code-style issues before I saw your comment about making this compatible with Python 2.7. With the updates in commit `0dfb1b7`, the script runs OK with Python 3.6 and does not cause any errors when pylint is used with Python 2.7:

```
HDoupe-MacBook-Pro:policybrain-builder henrydoupe$ source activate py27
(py27) HDoupe-MacBook-Pro:policybrain-builder henrydoupe$ python --version
Python 2.7.15 :: Anaconda, Inc.
(py27) HDoupe-MacBook-Pro:policybrain-builder henrydoupe$ pylint builder.py 
No config file found, using default configuration
************* Module builder
C:  1, 0: Missing module docstring (missing-docstring)
W: 28,-1: String statement has no effect (pointless-string-statement)
W: 60, 8: Redefining name 'cmd' from outer scope (line 118) (redefined-outer-name)
W: 70,21: Redefining name 'python_version' from outer scope (line 130) (redefined-outer-name)
W: 70,37: Redefining name 'package' from outer scope (line 114) (redefined-outer-name)
W: 70,46: Redefining name 'vers' from outer scope (line 114) (redefined-outer-name)
W: 77, 4: Redefining name 'cmd' from outer scope (line 118) (redefined-outer-name)
C: 87,11: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
E:114, 4: Possible unbalanced tuple unpacking with sequence: left side has 3 label(s), right side has 0 value(s) (unbalanced-tuple-unpacking)
C:114, 4: Constant name "repo" doesn't conform to UPPER_CASE naming style (invalid-name)
C:114,10: Constant name "package" doesn't conform to UPPER_CASE naming style (invalid-name)
C:114,19: Constant name "vers" doesn't conform to UPPER_CASE naming style (invalid-name)
C:118, 4: Constant name "cmd" doesn't conform to UPPER_CASE naming style (invalid-name)

------------------------------------------------------------------
Your code has been rated at 7.54/10 (previous run: 7.54/10, +0.00)

(py27) HDoupe-MacBook-Pro:policybrain-builder henrydoupe$ 
```

**Comment by martinholmer** [comment]
@hdoupe,  Thanks for making the `builder.py` script compatible with Python 2.7 in pull request #83.

But `builder.py` doesn't work.  I can use `pb` to build and upload packages for Tax-Calculator version 0.8.5 just fine.  But I cannot do that with `builder.py`.  Here is my experience on Python 2.7:
```
iMac:policybrain-builder mrh$ ./gitpr 83

iMac:policybrain-builder mrh$ git branch
  master
* pr-83

iMac:policybrain-builder mrh$ TOKEN=os-???77d   python builder.py Tax-Calculator taxcalc 0.8.5
('repo name', 'Tax-Calculator')
('package name', 'taxcalc')
('package version', '0.8.5')
('running', 'git clone https://github.com/open-source-economics/Tax-Calculator/')
Cloning into 'Tax-Calculator'...
remote: Counting objects: 28275, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 28275 (delta 1), reused 1 (delta 0), pack-reused 28271
Receiving objects: 100% (28275/28275), 891.96 MiB | 19.35 MiB/s, done.
Resolving deltas: 100% (21082/21082), done.
('running', 'git checkout -b v0.8.5 0.8.5')
Switched to a new branch 'v0.8.5'
('running', 'conda config --add channels ospc')
Warning: 'ospc' already in 'channels' list, moving to the top
('running', 'conda build conda.recipe --output-folder artifacts --no-anaconda-upload --python 2.7')
Attempting to finalize metadata for taxcalc
INFO:conda_build.metadata:Attempting to finalize metadata for taxcalc
Solving environment: done
Solving environment: done
BUILD START: [u'taxcalc-0.8.5-py27hb6cc402_0.tar.bz2']

... [SNIP] ...

TEST END: artifacts/osx-64/taxcalc-0.8.5-py27hb6cc402_0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload artifacts/osx-64/taxcalc-0.8.5-py27hb6cc402_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
('running', 'conda convert artifacts/osx-64/taxcalc-0.8.5-py27_0.tar.bz2 -p all -o artifacts/')
Traceback (most recent call last):
  File "/Users/mrh/anaconda2/bin/conda-convert", line 11, in <module>
    sys.exit(main())
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_convert.py", line 128, in main
    return execute(sys.argv[1:])
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_convert.py", line 124, in execute
    api.convert(f, **args.__dict__)
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 283, in convert
    dry_run=dry_run, dependencies=dependencies)
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/conda_build/convert.py", line 700, in conda_convert
    if len(retrieve_c_extensions(file_path)) > 0 and not force:
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/conda_build/convert.py", line 39, in retrieve_c_extensions
    with tarfile.open(file_path) as tar:
  File "/Users/mrh/anaconda2/lib/python2.7/tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "/Users/mrh/anaconda2/lib/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/Users/mrh/anaconda2/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: u'/Users/mrh/work/OSPC/policybrain-builder/Tax-Calculator/artifacts/osx-64/taxcalc-0.8.5-py27_0.tar.bz2'
Traceback (most recent call last):
  File "builder.py", line 131, in <module>
    build_and_upload(python_version, package, vers)
  File "builder.py", line 84, in build_and_upload
    python_string=python_string))
  File "builder.py", line 67, in run
    assert proc.poll() == 0
AssertionError
iMac:policybrain-builder mrh$ 
```

Any thoughts about the assert error?

Also, conda warned about adding the `ospc` channel earlier in the script:
```
('running', 'git checkout -b v0.8.5 0.8.5')
Switched to a new branch 'v0.8.5'
('running', 'conda config --add channels ospc')
Warning: 'ospc' already in 'channels' list, moving to the top . <=========================
('running', 'conda build conda.recipe --output-folder artifacts --no-anaconda-upload --python 2.7')
```

**Comment by hdoupe** [comment]
@martinholmer this line appears to be the issue:
`IOError: [Errno 2] No such file or directory: u'/Users/mrh/work/OSPC/policybrain-builder/Tax-Calculator/artifacts/osx-64/taxcalc-0.8.5-py27_0.tar.bz2'`

What is in the directory `/Users/mrh/work/OSPC/policybrain-builder/Tax-Calculator/artifacts/`?

(The assertion error arises because the unix command didn't exit correctly.)

The conda warning is normal. To my knowledge, it just affects the order in which the channels are searched.

**Comment by hdoupe** [comment]
When I run the script, I get the following outputs in the `artifacts` directory:
```
(base) root@9dee6ff31584:/home# ls Tax-Calculator/artifacts/
linux-32/      linux-64/      linux-aarch64/ linux-armv6l/  linux-armv7l/  linux-ppc64le/ noarch/        osx-64/        win-32/        win-64/        
(base) root@9dee6ff31584:/home# ls Tax-Calculator/artifacts/osx-64/
repodata.json  repodata.json.bz2  taxcalc-0.8.5-py27_0.tar.bz2	taxcalc-0.8.5-py36_0.tar.bz2
(base) root@9dee6ff31584:/home# 
```

**Comment by martinholmer** [comment]
@hdoupe,  Here is what was left behind when the `builder.py` script crashed:
```
iMac:policybrain-builder mrh$ ls Tax-Calculator/artifacts/
noarch	osx-64
iMac:policybrain-builder mrh$ ls Tax-Calculator/artifacts/osx-64/
repodata.json				taxcalc-0.8.5-py27hb6cc402_0.tar.bz2
repodata.json.bz2
iMac:policybrain-builder mrh$ 
```

**Comment by hdoupe** [comment]
Thanks @martinholmer. 

It looks like it's tacking on some type of hash after `py27`. I'm not sure why this is happening on your machine but not mine.

What happens if you run `conda build purge` and try the script again?

**Comment by hdoupe** [comment]
@martinholmer here's some documentation on the build artifact filename: https://conda.io/docs/user-guide/tasks/build-packages/package-naming-conv.html

I looked through the `conda-build` source code, but I didn't come anywhere close to figuring out where this path is constructed. I'm not really sure where it pulled the `hb6cc402` hash. I'm also not sure how to specify the output path.

Do you have any thoughts on this?

**Comment by martinholmer** [comment]
@hdoupe said in PR #83:
> It looks like it's [i.e., the `builder.py` script] tacking on some type of hash after py27.
> I'm not sure why this is happening on your machine but not mine.

Perhaps because I'm using a newer version of the conda-build package than you are?
On my computer I see this:
```
iMac:~ mrh$ conda list conda-build
# packages in environment at /Users/mrh/anaconda2:
#
# Name                    Version                   Build  Channel
conda-build               3.10.8                   py27_0  
```
What version of conda-build are you using?  My (wild) guess is that you have an earlier version.

My understanding is that the anaconda folks introduced the hash suffix in a recent version of conda-build.
Earlier versions of conda-build did not append hashes.  

There is a way, in the newer versions of conda-build, to suppress the hash suffix.  Joseph Crail, the author of the policybrain-builder CLI tool `pb`, handled this incompatibility between different versions of conda-build in this way:
```
def conda_build():
    _, version = u.check_output("conda build -V").strip().split()
    major = int(version.split('.')[0])
    if major >= 3:
        return "conda build --old-build-string"
    return "conda build"
```
The above code is from the policybrain_builder/cli/package.py` file.

Can you incorporate this kind of hash-suppression logic into your `builder.py` script?

**Comment by hdoupe** [comment]
@martinholmer Ah, nice job in uncovering this and seeing the connection. I'll make the update and push that up. 

I think I'm running the same version as you:
```
(py27) HDoupe-MacBook-Pro:policybrain-builder henrydoupe$ docker run -it builder:latest /bin/bash
(base) root@fbb51fe4b570:/home# conda list conda-build 
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
conda-build               3.10.8                   py36_0  
(base) root@fbb51fe4b570:/home# conda update conda-build
```

**Comment by hdoupe** [comment]
@martinholmer does commit `950a0e8` solve the problem?

**Comment by martinholmer** [comment]
@hdoupe, your commit 950a0e8 has made things much better.  Thanks.
However, there are still a number of things that need to be improved.

1. The `builder.py` script does not clean up after itself; it leaves the `policybrain_builder/Tax-Calculator directory tree that it created when making taxcalc packages.  This is not just untidy, but makes it so that you cannot run the `builder.py` script twice in a row.   Is there a reason to leave the downloaded repository clone after the script finishes?  If not, can  you add some clean-up code?  When building/uploading taxcalc, this command did the clean-up:
```policybrain_builder$ rm -rf Tax-Calculator```

2. The `builder.py` script would be much easier to use (and work for those using Windows) if you simply add as the very first command-line argument TOKEN.  The environment variable business adds only complications and remember Windows users don't have a shell that knows anything about ```export TOKEN = <mytoken>``` . Can you add the TOKEN as the first command-line parameter and make the associated code changes?

3. Shouldn't the `builder.py` docstring say something about the expected versions of `conda` and `conda-build`?  Maybe add something like this:  ```This script expects modern versions of conda and conda-build: conda>=4.5 and conda-build>=3.5```

**Comment by martinholmer** [comment]
@hdoupe,  Here is another big problem when the packages are built with `builder.py`:
```
Last login: Thu Jun 14 08:40:08 on ttys000
iMac:~ mrh$ conda install -c ospc taxcalc
Solving environment: done

## Package Plan ##

  environment location: /Users/mrh/anaconda2

  added / updated specs: 
    - taxcalc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    taxcalc-0.20.1             |           py27_0        38.1 MB  ospc

The following NEW packages will be INSTALLED:
    taxcalc: 0.20.1-py27_0 ospc

Proceed ([y]/n)? y

Downloading and Extracting Packages
taxcalc-0.20.1       | 38.1 MB | ####################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

iMac:~ mrh$ tc --version
Tax-Calculator unknown

iMac:~ mrh$ python 
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import taxcalc as tc
>>> tc.__version__
'unknown'
>>> exit()

iMac:~ mrh$ 
```
Why is the package version unknown?

**Comment by hdoupe** [comment]
@martinholmer I added a line of code to remove the repo after the build finishes, and I added documentation for which conda version the script expects.

I'm willing to address the issues you brought up at some point in the future. But, development is picking up in PolicyBrain, and I will be focusing more on that work. If you or anyone else is interested in continuing development on this script sooner, then I'd be happy to advise your or their efforts. So, I'm proposing that we merge the script as is and continue work on it as we have time or as others take interest. Does that seem sensible?

**Comment by martinholmer** [comment]
Merging this work in progress. The `builder.py` script needs more enhancements before it can be used with confidence. Until those enhancements are made, follow the directions in `README.md` on how to use the `pb` command-line package-build/upload tool.

**Pull request merged**
